services:
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ssl_certs:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django
      - react
    restart: unless-stopped
    networks:
      - transcendence-net

  django:
    container_name: django
    build: ./backend/
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: on-failure
    networks:
      - transcendence-net

  react:
    container_name: react
    build: ./frontend/
    expose:
      - "5173"
    restart: on-failure
    networks:
      - transcendence-net

volumes:
  ssl_certs:

networks:
  transcendence-net:
    driver: bridge