# Generated by Django 6.1.1 on 2026-09-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ftuser',
            old_name='created_at',
            new_name='user_created_at',
        ),
        migrations.RenameField(
            model_name='ftuser',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='ftuser',
            old_name='first_name',
            new_name='user_first_name',
        ),
        migrations.RenameField(
            model_name='ftuser',
            old_name='ft_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='ftuser',
            old_name='image_url',
            new_name='user_image_url',
        ),
        migrations.RenameField(
            model_name='ftuser',
            old_name='last_name',
            new_name='user_last_name',
        ),
        migrations.RenameField(
            model_name='ftuser',
            old_name='login',
            new_name='user_login',
        ),
        migrations.RenameField(
            model_name='ftuser',
            old_name='updated_at',
            new_name='user_updated_at',
        ),
        migrations.AddField(
            model_name='ftuser',
            name='user_kind',
            field=models.CharField(default='', max_length=50),
        ),
    ]
