# Generated by Django 6.1.1 on 2026-09-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0002_rename_created_at_ftuser_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wl_login', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
