# Generated by Django 6.1.1 on 2026-09-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0004_ftprofil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_id', models.IntegerField(unique=True)),
                ('profil_login', models.CharField(max_length=50)),
                ('profil_email', models.EmailField(max_length=254)),
                ('profil_first_name', models.CharField(max_length=100)),
                ('profil_last_name', models.CharField(max_length=100)),
                ('profil_image_url', models.URLField(blank=True)),
                ('profil_pool_year', models.CharField(max_length=4)),
                ('profil_pool_month', models.CharField(max_length=20)),
                ('profil_lvl', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('valid', models.BooleanField(default=False)),
                ('note', models.IntegerField(null=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth42.profil')),
            ],
        ),
        migrations.DeleteModel(
            name='FtProfil',
        ),
    ]
