# Generated by Django 6.1.1 on 2026-09-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0005_profil_projects_delete_ftprofil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='profil_lvl',
            field=models.FloatField(null=True),
        ),
    ]
