# Generated by Django 6.1.1 on 2026-09-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0006_alter_profil_profil_lvl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
