# Generated by Django 6.1.1 on 2026-09-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0007_rename_projects_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth42.ftuser')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth42.profil')),
            ],
        ),
    ]
