# Generated by Django 6.1.1 on 2026-09-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftuser',
            name='user_location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
