# Generated by Django 6.1.1 on 2026-09-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0009_ftuser_user_location_profil_profil_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='profil_afternoon_hours',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_correction_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_daily_average_hours',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_morning_hours',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_night_hours',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_peer_help',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_perseverance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_preferred_slot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_risk_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_risk_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_self_research',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_stress',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_timidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profil_total_hours',
            field=models.FloatField(null=True),
        ),
    ]
