# Generated by Django 6.1.1 on 2026-09-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0010_profil_profil_afternoon_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='profil_correction_points',
            new_name='profil_correction_point',
        ),
    ]
