# Generated by Django 6.1.1 on 2026-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0011_rename_profil_correction_points_profil_profil_correction_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftuser',
            name='user_followed',
            field=models.ManyToManyField(blank=True, to='auth42.profil'),
        ),
    ]
