# Generated by Django 6.1.1 on 2026-09-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0012_ftuser_user_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
