# Generated by Django 6.1.1 on 2026-09-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0014_alter_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_year', models.CharField(default='2026', max_length=4)),
                ('pool_month', models.CharField(default='september', max_length=20)),
            ],
        ),
    ]
