# Generated by Django 6.1.1 on 2026-10-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0015_syncconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='profil_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
