# Generated by Django 6.1.1 on 2026-10-05 07:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0016_profil_profil_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyXp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('level', models.FloatField(default=0.0)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_xp', to='auth42.profil')),
            ],
        ),
    ]
