# Generated by Django 6.1.1 on 2026-10-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0017_dailyxp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftuser',
            name='user_role',
            field=models.CharField(choices=[('staff', 'Staff'), ('tutor', 'Tutor')], default='tutor', max_length=20),
        ),
    ]
